steps:
- bash: curl -L -O https://github.com/sbt/sbt/releases/download/v1.0.4/sbt-1.0.4.zip
  displayName: Download SBT

- bash: unzip sbt-1.0.4.zip
  displayName: Expand SBT

- bash: ./sbt/bin/sbt package
  displayName: Build

- task: publishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)/target/scala-2.12/hello_2.12-0.1.0-SNAPSHOT.jar
    ArtifactName: helloworld-jar
    ArtifactType: Container