steps:
- bash: curl -L -O https://github.com/sbt/sbt/releases/download/v1.0.4/sbt-1.0.4.zip
  displayName: Download SBT

- bash: unzip sbt-1.0.4.zip
  displayName: Expand SBT

- bash: ./sbt/bin/sbt package
  displayName: Build
